#!/usr/bin/env python3

#Script Name: Directories
#Purpose: To provide all elements inside directory.
#Example usage: List of all elements inside specify target.
#Expected output: List of directotries, subdirectories and files
#variables: Direc

import os

dir = input("Provide directory path to analyze: ")
#Sets user input into a variable   
def directories(result):
    
    for (root, dirs, files) in os.walk(result):
        #Loops through input given to provide all the path branches, directories and files
        print ("\n", "The directories and files for the following path are below")
        print(root)
        # Prints all path branches
        print(dirs)
        # Prints all directories ans sub inside path
        print(files)
        # Prints all files inside path given

directories(dir)
#calls the function with the set parameter provided