#!/usr/bin/env python3

#Script Name: Directories
#Purpose: To provide all elements inside directory.
#Example usage: List of all elements inside specify target.
#Expected output: List of directotries, subdirectories and files
#variables: Direc

import os

dir = input("Please provide directory path: "  )
    #Sets user input into a variable   
print ()
def directories(result):
    
    for (root, dirs, files) in os.walk(result):
        #Loops through input given to provide all the path branches, directories and files
        print(root)
        print ("These are the directories, subdirectories and files in this path", "\n")
        # Prints all path branches
        print(dirs)
        # Prints all directories ans sub inside path
        print(files, "\n")
        # Prints all files inside path given

directories(dir)
#calls the function with the set parameter provided