#!/usr/bin/env python3

#Script Name: Files
#Purpose: Manipulation of a file.
#Example usage: To create a file, extract only needed information and delete the rest.
#Expected output: First line of the file.
#variables: File

import os

file = open("test.txt", "a")
#Creates and prepares the file for appending
file.write("This is the test file\n")
file.write("And we are appending lines\n")
file.write("Now we can delete it\n")
#Appends line to the file (only accept 1 parameter)
file = open("test.txt", "r")
#Prepare the file to be read
print(file.readline())
#Prints the first line (readlines will print it on a raw format)
file.close()
#Closes the file
os.remove("test.txt")
#Deletes the file